version: '3'
services:
  jobmanager:
    image: flink:1.20.1-scala_2.12 # Stable Java 11 Java flnk jobs, 17 experimental
    ports:
      - "8081:8081"
    volumes:
      - ./jars:/opt/flink/plugins/kafka/
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: flink:1.20.1-scala_2.12
    depends_on:
      - jobmanager
    volumes:
      - ./jars:/opt/flink/plugins/kafka/
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    deploy:
      replicas: 2
